-- Tabellen für den Regisseur (Sprint 09/2026): Material, Momente, Musik, Entwürfe, Bewertungen, Lern-Bot.
-- Nur portables SQL (Umzug nach Postgres, docs/ENTSCHEIDUNGEN.md E3):
--   INTEGER PRIMARY KEY -> in Postgres "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
--   Zeiten als ISO-Text in UTC, JSON als Text, Einfügen mit ON CONFLICT … DO …

-- Nachrichten an dich über den Lern-Bot (Alarme, Stand am Abend, Abschlussbericht) – je Schlüssel einmal
CREATE TABLE IF NOT EXISTS lern_meldungen (
    id         INTEGER PRIMARY KEY,
    schluessel TEXT NOT NULL UNIQUE,
    text       TEXT NOT NULL,
    erstellt   TEXT NOT NULL,
    gesendet   TEXT
);

-- Vom großen Host auf den Mini kopiertes Material (nur Kopien, Prüfsumme je Datei)
CREATE TABLE IF NOT EXISTS material (
    quelle        TEXT PRIMARY KEY,         -- Pfad relativ zur Speicher-Wurzel (/srv/clips)
    ziel          TEXT NOT NULL,            -- Pfad auf dem Mini
    art           TEXT NOT NULL CHECK (art IN ('replay', 'session', 'video', 'video_ende')),
    groesse       INTEGER NOT NULL,         -- Größe der Quelle in Bytes
    sha256_quelle TEXT NOT NULL,
    sha256_ziel   TEXT NOT NULL,            -- gleich sha256_quelle, außer bei video_ende (gekürzt)
    von_s         REAL,                     -- video_ende: Start des Ausschnitts in der Quelle
    kopiert       TEXT NOT NULL
);

-- Ein Moment = ein Stück Video mit einer Stimmung (meist ein Clip der Pipeline)
CREATE TABLE IF NOT EXISTS momente (
    id         INTEGER PRIMARY KEY,
    schluessel TEXT NOT NULL UNIQUE,        -- z. B. clip:42 oder datei:<pfad>
    clip_id    INTEGER,
    match_id   TEXT,
    datei      TEXT NOT NULL,               -- Videodatei (absolut)
    start_s    REAL NOT NULL,
    ende_s     REAL NOT NULL,
    start_utc  TEXT,
    kills      INTEGER NOT NULL DEFAULT 0,
    stimmung   TEXT NOT NULL CHECK (stimmung IN ('episch', 'lustig', 'spannend', 'frustriert', 'chill')),
    sicherheit REAL NOT NULL,               -- 0..1: wie klar die Regeln waren
    quelle     TEXT NOT NULL,               -- regel | claude
    merkmale   TEXT NOT NULL,               -- JSON: Spitzen, Lachen, Jubel, Kills, Tod, Energie …
    text       TEXT,                        -- Transkript der Mikro-Spur (faster-whisper)
    erstellt   TEXT NOT NULL,
    geaendert  TEXT NOT NULL
);

-- Musik (NCS o. ä.) mit Quellenangabe, Tempo und Energie
CREATE TABLE IF NOT EXISTS tracks (
    id         INTEGER PRIMARY KEY,
    datei      TEXT NOT NULL UNIQUE,        -- Dateiname im Musik-Ordner
    titel      TEXT NOT NULL,
    kuenstler  TEXT,
    quelle     TEXT NOT NULL,               -- Quellenangabe/Lizenz (kommt in die Beschreibung)
    sha256     TEXT NOT NULL,
    dauer_s    REAL,
    bpm        REAL,
    energie    REAL,                        -- 0..1
    beats      TEXT,                        -- JSON: Beat-Zeitpunkte in Sekunden
    stimmungen TEXT,                        -- JSON: passende Stimmungen (abgeleitet)
    erstellt   TEXT NOT NULL
);

-- Ein Entwurf = eine Schnittliste (compose) und ihr Video
CREATE TABLE IF NOT EXISTS entwuerfe (
    id              INTEGER PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    format          TEXT NOT NULL CHECK (format IN ('zusammenschnitt', 'short')),
    schnittliste    TEXT NOT NULL,          -- Pfad zur JSON
    parameter       TEXT NOT NULL,          -- JSON: gelernte Regie-Parameter beim Erzeugen
    track_id        INTEGER,
    dauer_s         REAL,
    datei           TEXT,                   -- Entwurf (klein, Telegram)
    final_datei     TEXT,                   -- finale Qualität (pve-big, NVENC)
    status          TEXT NOT NULL DEFAULT 'neu' CHECK (status IN ('neu', 'gerendert', 'gesendet', 'bewertet')),
    tg_nachricht_id INTEGER,
    erstellt        TEXT NOT NULL
);

-- Deine Bewertung eines Entwurfs: Daumen plus Gründe
CREATE TABLE IF NOT EXISTS entwurf_bewertungen (
    entwurf_id INTEGER PRIMARY KEY REFERENCES entwuerfe (id),
    daumen     INTEGER NOT NULL CHECK (daumen IN (-1, 1)),
    gruende    TEXT NOT NULL DEFAULT '[]',  -- JSON-Liste aus den festen Gründen
    erstellt   TEXT NOT NULL,
    geaendert  TEXT NOT NULL
);
