-- Tabellen für den Regisseur (Sprint 09/2026): Material, Momente, Musik, Entwürfe, Bewertungen, Lern-Bot.
-- Nur portables SQL (Umzug nach Postgres, docs/ENTSCHEIDUNGEN.md E3):
--   INTEGER PRIMARY KEY -> in Postgres "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
--   Zeiten als ISO-Text in UTC, JSON als Text, Einfügen mit ON CONFLICT … DO …

-- Nachrichten an dich über den Lern-Bot (Alarme, Stand am Abend, Abschlussbericht) – je Schlüssel einmal
CREATE TABLE IF NOT EXISTS lern_meldungen (
    id         INTEGER PRIMARY KEY,
    schluessel TEXT NOT NULL UNIQUE,
    text       TEXT NOT NULL,
    erstellt   TEXT NOT NULL,
    gesendet   TEXT
);

-- Vom großen Host auf den Mini kopiertes Material (nur Kopien, Prüfsumme je Datei)
CREATE TABLE IF NOT EXISTS material (
    quelle        TEXT PRIMARY KEY,         -- Pfad relativ zur Speicher-Wurzel (/srv/clips)
    ziel          TEXT NOT NULL,            -- Pfad auf dem Mini
    art           TEXT NOT NULL CHECK (art IN ('replay', 'session', 'video', 'video_ende')),
    groesse       INTEGER NOT NULL,         -- Größe der Quelle in Bytes
    sha256_quelle TEXT NOT NULL,
    sha256_ziel   TEXT NOT NULL,            -- gleich sha256_quelle, außer bei video_ende (gekürzt)
    von_s         REAL,                     -- video_ende: Start des Ausschnitts in der Quelle
    kopiert       TEXT NOT NULL
);

-- Ein Moment = ein Stück Video mit einer Stimmung (meist ein Clip der Pipeline)
CREATE TABLE IF NOT EXISTS momente (
    id         INTEGER PRIMARY KEY,
    schluessel TEXT NOT NULL UNIQUE,        -- z. B. clip:42 oder datei:<pfad>
    clip_id    INTEGER,
    match_id   TEXT,
    datei      TEXT NOT NULL,               -- Videodatei (absolut)
    start_s    REAL NOT NULL,
    ende_s     REAL NOT NULL,
    start_utc  TEXT,
    kills      INTEGER NOT NULL DEFAULT 0,
    stimmung   TEXT NOT NULL CHECK (stimmung IN ('episch', 'lustig', 'spannend', 'frustriert', 'chill')),
    sicherheit REAL NOT NULL,               -- 0..1: wie klar die Regeln waren
    quelle     TEXT NOT NULL,               -- regel | claude
    merkmale   TEXT NOT NULL,               -- JSON: Spitzen, Lachen, Jubel, Kills, Tod, Energie …
    text       TEXT,                        -- Transkript der Mikro-Spur (faster-whisper)
    erstellt   TEXT NOT NULL,
    geaendert  TEXT NOT NULL
);

-- Musik (NCS o. ä.) mit Quellenangabe, Tempo und Energie
CREATE TABLE IF NOT EXISTS tracks (
    id         INTEGER PRIMARY KEY,
    datei      TEXT NOT NULL UNIQUE,        -- Dateiname im Musik-Ordner
    titel      TEXT NOT NULL,
    kuenstler  TEXT,
    quelle     TEXT NOT NULL,               -- Quellenangabe/Lizenz (kommt in die Beschreibung)
    sha256     TEXT NOT NULL,
    dauer_s    REAL,
    bpm        REAL,
    energie    REAL,                        -- 0..1
    beats      TEXT,                        -- JSON: Beat-Zeitpunkte in Sekunden
    verlauf    TEXT,                        -- JSON: Energie je Sekunde (0..1), zeigt Aufbau und Drop
    stimmungen TEXT,                        -- JSON: passende Stimmungen (abgeleitet)
    erstellt   TEXT NOT NULL
);

-- Ein Entwurf = eine Schnittliste (compose) und ihr Video
CREATE TABLE IF NOT EXISTS entwuerfe (
    id              INTEGER PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    format          TEXT NOT NULL CHECK (format IN ('zusammenschnitt', 'short')),
    schnittliste    TEXT NOT NULL,          -- Pfad zur JSON
    parameter       TEXT NOT NULL,          -- JSON: gelernte Regie-Parameter beim Erzeugen
    track_id        INTEGER,
    dauer_s         REAL,
    datei           TEXT,                   -- Entwurf (klein, Telegram)
    final_datei     TEXT,                   -- finale Qualität (pve-big, NVENC)
    status          TEXT NOT NULL DEFAULT 'neu' CHECK (status IN ('neu', 'gerendert', 'gesendet', 'bewertet')),
    tg_nachricht_id INTEGER,
    erstellt        TEXT NOT NULL
);

-- Deine Bewertung eines Entwurfs: Daumen plus Gründe
CREATE TABLE IF NOT EXISTS entwurf_bewertungen (
    entwurf_id INTEGER PRIMARY KEY REFERENCES entwuerfe (id),
    daumen     INTEGER NOT NULL CHECK (daumen IN (-1, 1)),
    gruende    TEXT NOT NULL DEFAULT '[]',  -- JSON-Liste aus den festen Gründen
    erstellt   TEXT NOT NULL,
    geaendert  TEXT NOT NULL
);

-- "Session vorbei"-Meldungen des Gaming-PCs (Datei sitzungen/<name>.json auf dem Speicher)
CREATE TABLE IF NOT EXISTS sitzungen (
    name        TEXT PRIMARY KEY,
    matches     TEXT NOT NULL,              -- JSON-Liste der Session-IDs (Replays) des Abends
    ende_utc    TEXT,
    entwurf_id  INTEGER,
    hinweis     TEXT,
    verarbeitet TEXT NOT NULL
);

-- Einstellungen aus dem Lern-Bot (⚙️, 29.09.): gehen vor config/lokal.toml und pipeline.toml.
-- Nur Schlüssel aus einstellungen.KATALOG werden angewendet; „↩️ Standard“ löscht die Zeile.
CREATE TABLE IF NOT EXISTS einstellungen (
    schluessel TEXT PRIMARY KEY,            -- Punkt-Pfad in der Konfig, z. B. lernbot.quelle
    wert       TEXT NOT NULL,               -- JSON
    geaendert  TEXT NOT NULL
);

-- Cutter-Kritik (Regisseur 3.0, 30.09.): der Bot benotet jeden Entwurf selbst – Handwerksregeln aus der Schnittliste
-- plus (optional) Claude als Senior-Cutter auf einem Kontaktbogen. Grundlage für Stilwahl, Selbst-Aussortieren und
-- automatische Gründe im Regie-Lernen; ersetzt dein 👍/👎 nicht, braucht es aber nicht.
CREATE TABLE IF NOT EXISTS kritiken (
    entwurf_id  INTEGER PRIMARY KEY REFERENCES entwuerfe (id),
    score       REAL NOT NULL,              -- 0..100 (Regeln und KI gemittelt, ohne KI nur Regeln)
    regel_score REAL NOT NULL,
    ki_score    REAL,                       -- NULL = keine KI-Kritik (aus, Tageslimit, Fehler)
    daumen      INTEGER,                    -- aus dem KI-Urteil: +1 ab [regie.kritik].gut_ab, sonst −1; NULL ohne KI
    gruende     TEXT NOT NULL DEFAULT '[]', -- JSON: Schlüssel aus regie_lernen.GRUENDE (vom KI-Cutter)
    details     TEXT NOT NULL,              -- JSON: Regel-Teile, Stärken, Schwächen, Hinweis
    erstellt    TEXT NOT NULL
);

-- Cutter-Maßstab 1.0 (30.09., kriterien.py/massstab.py): gelernte Faktoren f_k je Kriterium, eine Zeile je Version.
-- Neue Version nur, wenn sich input_hash (Paare + Einstellungen) ändert. Gelernt wird nur aus Lehrern, die die Note
-- nicht kennen (KI-Cutter blind, Publikum, dein 👍/👎) – nie aus kritiken.score/regel_score (Zirkelschluss).
CREATE TABLE IF NOT EXISTS massstab (
    version             INTEGER PRIMARY KEY,
    erstellt            TEXT NOT NULL,
    input_hash          TEXT NOT NULL UNIQUE,
    faktoren            TEXT NOT NULL,      -- JSON {k: f_k} wirksam (nach Vertrauen/Schranke)
    gelernt             TEXT NOT NULL,      -- JSON {k: f_k} roh
    start               TEXT NOT NULL,      -- JSON {format: {k: w0}}
    paare               TEXT NOT NULL,      -- JSON {"ki": n, "du": n, "publikum": n}
    datenbasis          INTEGER NOT NULL,   -- Entwürfe in mindestens einem Paar
    vertrauen           REAL NOT NULL,
    publikum_anteil     REAL NOT NULL,      -- π = n_pub / (n_pub + publikum_halb)
    ki_lehrer           REAL,               -- a_KI: so stark zählt der KI-Cutter als Lehrer
    ki_treffer_publikum REAL,               -- q_KI: Anteil Publikumspaare, die der KI-Cutter richtig sortiert
    quote_holdout       REAL,
    quote_holdout_start REAL,
    aktiv               INTEGER NOT NULL,
    grund               TEXT NOT NULL
);
